_layout: "patternbot_pattern_internal"
_extra_css:
  - 'brand/brand.min.css'

patterns:
  logos:
    title: "Logos"
    popout_button: false
    resizable: false
    code: false

  colours:
    title: "Colours"
    popout_button: false
    resizable: false
    code: false

  typefaces:
    title: "Typefaces"
    popout_button: false
    resizable: false
    code: false
