patternbot:
  source: "_patterns"
  destination: "pattern-library"
  css:
    source: "css"
    modulifier: "modules.css"
    gridifier: "grid.css"
    typografier: "type.css"
    theme: "theme.css"
  icons:
    source: "images/icons.svg"
